# Generated by Drydock — arm64 bun SSR image from ./landing.
FROM oven/bun:1.3-alpine AS build
WORKDIR /app/landing
COPY landing/package.json landing/bun.lock ./
RUN bun install --frozen-lockfile
WORKDIR /app
COPY . .
WORKDIR /app/landing
RUN bun run build

FROM oven/bun:1.3-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app /app
WORKDIR /app/landing
EXPOSE 3000
CMD ["sh", "-c", "bun run start"]
